import type { DBRefLinkPlatform } from "$/db/schema";

export const EMOJIS = {
	ARROW_DOWN: "⬇️",
	ARROW_LEFT: "⬅️",
	ARROW_RIGHT: "➡️",
	ARROW_UP: "⬆️",
	BAR_CHART: "📊",
	BOOK: "📖",
	BULB: "💡",
	CRESCENT_MOON: "🌙",
	DROPLET: "💧",
	EIGHT_BALL: "🎱",
	GEAR: "⚙️",
	GEM: "💎",
	GRAD_CAP: "🎓",
	GREEN_CHECK: "✅",
	HAND_WAVE: "👋",
	HEAR: "🦻",
	LABEL: "🏷",
	LINK: "🔗",
	LOCK: "🔒",
	MAG_GLASS: "🔍",
	MALE_DEV: "🧑🏻‍💻",
	MANTLE_CLOCK: "🕰",
	MEMO: "📝",
	MONEY_WINGS: "💸",
	MOUNTAIN: "⛰",
	PENCIL: "✏️",
	PILL: "💊",
	POINT_DOWN: "👇",
	POLICE_SIREN: "🚨",
	RED_QUESTION: "❓",
	RED_X: "❌",
	SPORTS_MEDAL: "🏅",
	STOP_SIGN: "🛑",
	WARNING: "⚠️",
};

export const REF_PLATFORMS: DBRefLinkPlatform[] = ["bonk", "bullx", "maestro", "photon", "shuriken", "trojan"];
